// ============================================================
// Feature 7: Export utilities — CSV and Markdown
// ============================================================

import type { SessionResponse } from "@/lib/types";

/**
 * Converts a session's data to a CSV string.
 */
export function toCSV(session: SessionResponse): string {
  const lines: string[] = [];

  // Header
  lines.push("Section,Field,Value");

  // Session metadata
  const reportName = session.report?.displayName || "Team Member";
  const date = new Date(session.occurredAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  lines.push(`Session,Date,"${date}"`);
  lines.push(`Session,Team Member,"${reportName}"`);
  lines.push(`Session,Label,"${session.label || "1:1 Meeting"}"`);

  // Metrics
  if (session.metrics) {
    const m = session.metrics;
    lines.push(`Metrics,Manager Talk %,${m.managerTalkPct}`);
    lines.push(`Metrics,Report Talk %,${m.reportTalkPct}`);
    lines.push(`Metrics,Manager Questions,${m.managerQuestions}`);
    lines.push(`Metrics,Report Questions,${m.reportQuestions}`);
    lines.push(`Metrics,Manager Initiated Topics,${m.managerInitiatedTopics}`);
    lines.push(`Metrics,Report Initiated Topics,${m.reportInitiatedTopics}`);
    lines.push(`Metrics,Flagged,${m.flagged ? "Yes" : "No"}`);
    if (m.flagReason) {
      lines.push(`Metrics,Flag Reason,"${m.flagReason}"`);
    }
  }

  // Action items
  if (session.actionItems.length > 0) {
    lines.push("");
    lines.push("Action Items,Owner,Text,Due,Status");
    for (const item of session.actionItems) {
      const escapedText = item.text.replace(/"/g, '""');
      lines.push(
        `Action Item,"${item.speakerRole === "manager" ? "Manager" : "Report"}","${escapedText}","${item.dueHint || ""}","${item.status}"`
      );
    }
  }

  return lines.join("\n");
}

/**
 * Triggers a browser download of the CSV.
 */
export function downloadCSV(session: SessionResponse): void {
  const csv = toCSV(session);
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  const reportName = session.report?.displayName?.replace(/\s+/g, "-") || "session";
  const date = new Date(session.occurredAt).toISOString().split("T")[0];
  link.href = url;
  link.download = `1on1-${reportName}-${date}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Converts a session to a clean Markdown summary for pasting into Notion/Confluence.
 */
export function toMarkdown(session: SessionResponse): string {
  const reportName = session.report?.displayName || "Team Member";
  const date = new Date(session.occurredAt).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const lines: string[] = [];

  lines.push(`# 1:1 Session — ${reportName}`);
  lines.push(`**Date:** ${date}`);
  lines.push(`**Meeting Type:** ${session.label || "1:1 Meeting"}`);
  lines.push("");

  if (session.metrics) {
    const m = session.metrics;
    lines.push("## 📊 Talk-Time Metrics");
    lines.push(`| Participant | Talk % | Questions | Topics Initiated |`);
    lines.push(`|-------------|--------|-----------|-----------------|`);
    lines.push(
      `| Manager | **${m.managerTalkPct}%** | ${m.managerQuestions} | ${m.managerInitiatedTopics} |`
    );
    lines.push(
      `| ${reportName} | **${m.reportTalkPct}%** | ${m.reportQuestions} | ${m.reportInitiatedTopics} |`
    );
    lines.push("");

    if (m.flagged) {
      lines.push(`> ⚠️ **Flagged:** ${m.flagReason || "Manager talk-time exceeded threshold"}`);
      lines.push("");
    }

    if (m.summary) {
      lines.push("## 🤖 AI Summary");
      lines.push(m.summary);
      lines.push("");
    }
  }

  if (session.actionItems.length > 0) {
    const openItems = session.actionItems.filter((a) => a.status === "open");
    const doneItems = session.actionItems.filter((a) => a.status === "done");

    if (openItems.length > 0) {
      lines.push("## ✅ Open Action Items");
      for (const item of openItems) {
        const due = item.dueHint ? ` *(${item.dueHint})*` : "";
        const owner = item.speakerRole === "manager" ? "👤 Manager" : "👥 Report";
        lines.push(`- [ ] ${item.text}${due} — ${owner}`);
      }
      lines.push("");
    }

    if (doneItems.length > 0) {
      lines.push("## ✔️ Completed Items");
      for (const item of doneItems) {
        lines.push(`- [x] ${item.text}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by 1:1 Balance Studio*");

  return lines.join("\n");
}
